In [124]:
from tqdm import tqdm
import json
from PIL import Image
import pandas as pd

In [139]:
lines = ''
root_dir = '\\\\databrick\\Active Server Drive\\log_dir\\eve_miner'
with open(f"{root_dir}\\miner_2023-03-11_17-54-52_237157.log") as f:
    lines = f.readlines()

In [140]:
mining_class_lines = []
for line in tqdm(lines):
    if 'MiningBot.BotActions.Actions:mine_till_full_v2:311' in line:
        index = line.find('{')
        mining_class_lines.append(json.loads(line[index:-1].replace("'", '"').replace('UUID("', '"').replace('")', '"').replace("True", '1').replace("False", '0')))

100%|████████████████████████████████████████████████████████████████████████████████████████| 353/353 [00:00<?, ?it/s]

In [141]:
len(mining_class_lines)

10

In [142]:
mining_class_lines[0]

{'argmax_index': 4,
 'value_at_argmax': 0.99997413,
 'pass_general_tollerance': 1,
 'class': 'no_miners_running',
 'classes': ['both_running',
  'invalid',
  'miner_1_running',
  'miner_2_running',
  'no_miners_running'],
 'scores': [2.0456177480809856e-06,
  1.0142034625459928e-06,
  1.929081008711364e-05,
  3.5645834941533394e-06,
  0.9999741315841675],
 'id': 'ea8b7f63-c069-11ed-b52b-9c5c8ec2126c',
 'model': 'mining_tool_state'}

In [143]:
df = pd.DataFrame(mining_class_lines)
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,4,0.999974,1,no_miners_running,"[both_running, invalid, miner_1_running, miner...","[2.0456177480809856e-06, 1.0142034625459928e-0...",ea8b7f63-c069-11ed-b52b-9c5c8ec2126c,mining_tool_state
1,0,0.999998,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999984502792358, 2.6794932939111504e-09, 7...",07377091-c06a-11ed-b61c-9c5c8ec2126c,mining_tool_state
2,0,0.999999,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999992847442627, 1.96393123985672e-09, 6.3...",1dbf0016-c06a-11ed-919c-9c5c8ec2126c,mining_tool_state
3,0,1.000000,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999998807907104, 8.854580263450984e-11, 1....",33fa9e21-c06a-11ed-9774-9c5c8ec2126c,mining_tool_state
4,0,1.000000,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999998807907104, 1.6793814949789265e-10, 1...",4acb6a65-c06a-11ed-a3fe-9c5c8ec2126c,mining_tool_state
5,3,0.999999,1,miner_2_running,"[both_running, invalid, miner_1_running, miner...","[3.4728233799796726e-07, 1.0135140543119335e-1...",61297033-c06a-11ed-98d7-9c5c8ec2126c,mining_tool_state
6,0,0.999998,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999980926513672, 5.695455218557299e-10, 5....",7c5e1c23-c06a-11ed-bb64-9c5c8ec2126c,mining_tool_state
7,0,0.999990,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999897480010986, 5.056417784476963e-11, 1....",92c1576f-c06a-11ed-93f3-9c5c8ec2126c,mining_tool_state
8,0,1.000000,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999998807907104, 1.1476986722103177e-10, 1...",a909116f-c06a-11ed-a6e0-9c5c8ec2126c,mining_tool_state
9,2,1.000000,1,miner_1_running,"[both_running, invalid, miner_1_running, miner...","[1.240115068412706e-07, 2.2771017427203333e-07...",bfd598ed-c06a-11ed-8fed-9c5c8ec2126c,mining_tool_state

In [144]:
df = df.sort_values(by='value_at_argmax', ascending=True).reset_index()
del df['index']
df[0:20]

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,4,0.999974,1,no_miners_running,"[both_running, invalid, miner_1_running, miner...","[2.0456177480809856e-06, 1.0142034625459928e-0...",ea8b7f63-c069-11ed-b52b-9c5c8ec2126c,mining_tool_state
1,0,0.999990,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999897480010986, 5.056417784476963e-11, 1....",92c1576f-c06a-11ed-93f3-9c5c8ec2126c,mining_tool_state
2,0,0.999998,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999980926513672, 5.695455218557299e-10, 5....",7c5e1c23-c06a-11ed-bb64-9c5c8ec2126c,mining_tool_state
3,0,0.999998,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999984502792358, 2.6794932939111504e-09, 7...",07377091-c06a-11ed-b61c-9c5c8ec2126c,mining_tool_state
4,3,0.999999,1,miner_2_running,"[both_running, invalid, miner_1_running, miner...","[3.4728233799796726e-07, 1.0135140543119335e-1...",61297033-c06a-11ed-98d7-9c5c8ec2126c,mining_tool_state
5,0,0.999999,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999992847442627, 1.96393123985672e-09, 6.3...",1dbf0016-c06a-11ed-919c-9c5c8ec2126c,mining_tool_state
6,2,1.000000,1,miner_1_running,"[both_running, invalid, miner_1_running, miner...","[1.240115068412706e-07, 2.2771017427203333e-07...",bfd598ed-c06a-11ed-8fed-9c5c8ec2126c,mining_tool_state
7,0,1.000000,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999998807907104, 8.854580263450984e-11, 1....",33fa9e21-c06a-11ed-9774-9c5c8ec2126c,mining_tool_state
8,0,1.000000,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999998807907104, 1.6793814949789265e-10, 1...",4acb6a65-c06a-11ed-a3fe-9c5c8ec2126c,mining_tool_state
9,0,1.000000,1,both_running,"[both_running, invalid, miner_1_running, miner...","[0.9999998807907104, 1.1476986722103177e-10, 1...",a909116f-c06a-11ed-a6e0-9c5c8ec2126c,mining_tool_state

In [147]:
low_performing_list = df[df['value_at_argmax'] <=1]['id'].tolist()
low_performing_list
#Image.open(f"{root_dir}\\{df[0:2]['id'].tolist()[0]}.png")

['ea8b7f63-c069-11ed-b52b-9c5c8ec2126c',
 '92c1576f-c06a-11ed-93f3-9c5c8ec2126c',
 '7c5e1c23-c06a-11ed-bb64-9c5c8ec2126c',
 '07377091-c06a-11ed-b61c-9c5c8ec2126c',
 '61297033-c06a-11ed-98d7-9c5c8ec2126c',
 '1dbf0016-c06a-11ed-919c-9c5c8ec2126c',
 'bfd598ed-c06a-11ed-8fed-9c5c8ec2126c',
 '33fa9e21-c06a-11ed-9774-9c5c8ec2126c',
 '4acb6a65-c06a-11ed-a3fe-9c5c8ec2126c',
 'a909116f-c06a-11ed-a6e0-9c5c8ec2126c']

In [148]:
import shutil
for item in low_performing_list:
    shutil.move(f"{root_dir}\\{item}.png", f"O:\\source\\repos\\EVE-Online-Bot\\training_data\\unclass\\{item}.png")