In [24]:
from tqdm import tqdm
import json
from PIL import Image
import pandas as pd

In [25]:
lines = ''
root_dir = '\\\\databrick\\Active Server Drive\\log_dir\\eve_miner'
with open(f"{root_dir}\\miner_2023-03-11_19-45-26_743652.log") as f:
    lines = f.readlines()

In [26]:
class_lines = []
for line in tqdm(lines):
    if 'Current Screen Classification:' in line or 'Current Screen:' in line:
        index = line.find('{')
        class_lines.append(json.loads(line[index:-1].replace("'", '"').replace('UUID("', '"').replace('")', '"').replace("True", '1').replace("False", '0')))

100%|█████████████████████████████████████████████████████████████████████████| 1159/1159 [00:00<00:00, 1159360.44it/s]

In [27]:
len(class_lines)

31

In [28]:
class_lines[0]

{'argmax_index': 2,
 'value_at_argmax': 0.9999939,
 'pass_general_tollerance': 1,
 'class': 'in_flight',
 'classes': ['char_select', 'connection_lost', 'in_flight', 'in_hanger'],
 'scores': [7.466279612344806e-07,
  5.711110020456545e-07,
  0.9999939203262329,
  4.749661911773728e-06],
 'id': 'e51a3ef3-c077-11ed-b603-9c5c8ec2126c',
 'model': 'game_state'}

In [29]:
df = pd.DataFrame(class_lines)
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,2,0.999994,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[7.466279612344806e-07, 5.711110020456545e-07,...",e51a3ef3-c077-11ed-b603-9c5c8ec2126c,game_state
1,2,0.999994,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[7.445303822350979e-07, 5.758351449003385e-07,...",e76698b1-c077-11ed-a9cc-9c5c8ec2126c,game_state
2,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.5785325047090737e-07, 3.090625284585258e-07...",109d28de-c078-11ed-a947-9c5c8ec2126c,game_state
3,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.6831188531796215e-07, 3.0859695243634633e-0...",3b16dcd2-c078-11ed-8077-9c5c8ec2126c,game_state
4,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.019966284995462e-08, 1.2364604629055975e-07...",6440534d-c078-11ed-b8f6-9c5c8ec2126c,game_state
5,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2968820328751463e-07, 2.556671745423955e-07...",8d6b9004-c078-11ed-b784-9c5c8ec2126c,game_state
6,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2797659110219683e-07, 2.474126574725233e-07...",b690f737-c078-11ed-990a-9c5c8ec2126c,game_state
7,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.3998263170833525e-07, 2.8870840651507024e-0...",dfd6cc18-c078-11ed-8da8-9c5c8ec2126c,game_state
8,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.280442347706412e-07, 2.457751975271094e-07,...",0902b69b-c079-11ed-9b37-9c5c8ec2126c,game_state
9,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2530730941762158e-07, 2.48987902295994e-07,...",3227d4d7-c079-11ed-afd0-9c5c8ec2126c,game_state
10,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2489749678934459e-07, 2.4760362293818616e-0...",325bb576-c079-11ed-bd92-9c5c8ec2126c,game_state
11,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2800138904367486e-07, 2.474832569987484e-07...",5b887e48-c079-11ed-879b-9c5c8ec2126c,game_state
12,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2280059991098824e-07, 2.476888880664774e-07...",8509ecca-c079-11ed-ad3c-9c5c8ec2126c,game_state
13,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.673504308693737e-08, 1.4845763018911384e-07...",ae2e582b-c079-11ed-a85d-9c5c8ec2126c,game_state
14,3,0.999378,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[7.200213758551399e-07, 1.143569443229353e-05,...",c7f94c7d-c07a-11ed-a56b-9c5c8ec2126c,game_state
15,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.104458533518482e-07, 8.559667463714504e-08,...",ef9c6a51-c07a-11ed-85cd-9c5c8ec2126c,game_state
16,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.1993327575510193e-07, 1.0045284426496437e-0...",f1dbb5f3-c07a-11ed-8241-9c5c8ec2126c,game_state
17,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2076469602106954e-07, 1.1096024365997437e-0...",f21bbdca-c07a-11ed-990a-9c5c8ec2126c,game_state
18,3,0.999563,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[6.404005148397118e-07, 9.769660209713038e-06,...",a51e0ccb-c07d-11ed-947a-9c5c8ec2126c,game_state
19,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.3749803429163876e-07, 1.507889919594163e-07...",ccabceed-c07d-11ed-af4d-9c5c8ec2126c,game_state
20,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.700952623195917e-07, 1.2504513335898082e-07...",cef11e74-c07d-11ed-a6b7-9c5c8ec2126c,game_state
21,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.677412342360185e-07, 1.3253311692551506e-07...",cf32bb6c-c07d-11ed-97eb-9c5c8ec2126c,game_state
22,3,0.998738,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.486684368501301e-06, 2.0628771380870603e-05...",7bbba8ce-c07e-11ed-aa35-9c5c8ec2126c,game_state
23,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.6153693138676317e-07, 1.7850081235337711e-0...",a342863a-c07e-11ed-9859-9c5c8ec2126c,game_state
24,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.5589033353080595e-07, 1.1761855489567097e-0...",a58df3a1-c07e-11ed-9ce1-9c5c8ec2126c,game_state
25,3,0.998937,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.2608427368832054e-06, 1.8177783204009756e-0...",28e98fc3-c07f-11ed-9e2b-9c5c8ec2126c,game_state
26,2,0.999985,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.908632950493484e-06, 6.684096547360241e-07,...",5081b16e-c07f-11ed-aa13-9c5c8ec2126c,game_state
27,2,0.999984,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.978552629429032e-06, 6.222254000931571e-07,...",52cc6900-c07f-11ed-a72c-9c5c8ec2126c,game_state
28,3,0.998821,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.4172029523251695e-06, 1.956938831426669e-05...",d634c256-c07f-11ed-959d-9c5c8ec2126c,game_state
29,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.677986412270911e-08, 1.0937725392068387e-07...",fdd1bc30-c07f-11ed-999e-9c5c8ec2126c,game_state
30,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.288114455330287e-08, 8.098673021095237e-08,...",001d8023-c080-11ed-a473-9c5c8ec2126c,game_state

In [31]:
df = df.sort_values(by='value_at_argmax', ascending=True).reset_index()
del df['index']
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,3,0.998738,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.486684368501301e-06, 2.0628771380870603e-05...",7bbba8ce-c07e-11ed-aa35-9c5c8ec2126c,game_state
1,3,0.998821,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.4172029523251695e-06, 1.956938831426669e-05...",d634c256-c07f-11ed-959d-9c5c8ec2126c,game_state
2,3,0.998937,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.2608427368832054e-06, 1.8177783204009756e-0...",28e98fc3-c07f-11ed-9e2b-9c5c8ec2126c,game_state
3,3,0.999378,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[7.200213758551399e-07, 1.143569443229353e-05,...",c7f94c7d-c07a-11ed-a56b-9c5c8ec2126c,game_state
4,3,0.999563,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[6.404005148397118e-07, 9.769660209713038e-06,...",a51e0ccb-c07d-11ed-947a-9c5c8ec2126c,game_state
5,2,0.999984,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.978552629429032e-06, 6.222254000931571e-07,...",52cc6900-c07f-11ed-a72c-9c5c8ec2126c,game_state
6,2,0.999985,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.908632950493484e-06, 6.684096547360241e-07,...",5081b16e-c07f-11ed-aa13-9c5c8ec2126c,game_state
7,2,0.999994,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[7.466279612344806e-07, 5.711110020456545e-07,...",e51a3ef3-c077-11ed-b603-9c5c8ec2126c,game_state
8,2,0.999994,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[7.445303822350979e-07, 5.758351449003385e-07,...",e76698b1-c077-11ed-a9cc-9c5c8ec2126c,game_state
9,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.5785325047090737e-07, 3.090625284585258e-07...",109d28de-c078-11ed-a947-9c5c8ec2126c,game_state
10,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.6831188531796215e-07, 3.0859695243634633e-0...",3b16dcd2-c078-11ed-8077-9c5c8ec2126c,game_state
11,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.3998263170833525e-07, 2.8870840651507024e-0...",dfd6cc18-c078-11ed-8da8-9c5c8ec2126c,game_state
12,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2489749678934459e-07, 2.4760362293818616e-0...",325bb576-c079-11ed-bd92-9c5c8ec2126c,game_state
13,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2797659110219683e-07, 2.474126574725233e-07...",b690f737-c078-11ed-990a-9c5c8ec2126c,game_state
14,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.677986412270911e-08, 1.0937725392068387e-07...",fdd1bc30-c07f-11ed-999e-9c5c8ec2126c,game_state
15,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2530730941762158e-07, 2.48987902295994e-07,...",3227d4d7-c079-11ed-afd0-9c5c8ec2126c,game_state
16,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2280059991098824e-07, 2.476888880664774e-07...",8509ecca-c079-11ed-ad3c-9c5c8ec2126c,game_state
17,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.280442347706412e-07, 2.457751975271094e-07,...",0902b69b-c079-11ed-9b37-9c5c8ec2126c,game_state
18,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.6153693138676317e-07, 1.7850081235337711e-0...",a342863a-c07e-11ed-9859-9c5c8ec2126c,game_state
19,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2800138904367486e-07, 2.474832569987484e-07...",5b887e48-c079-11ed-879b-9c5c8ec2126c,game_state
20,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2968820328751463e-07, 2.556671745423955e-07...",8d6b9004-c078-11ed-b784-9c5c8ec2126c,game_state
21,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.3749803429163876e-07, 1.507889919594163e-07...",ccabceed-c07d-11ed-af4d-9c5c8ec2126c,game_state
22,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.288114455330287e-08, 8.098673021095237e-08,...",001d8023-c080-11ed-a473-9c5c8ec2126c,game_state
23,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.673504308693737e-08, 1.4845763018911384e-07...",ae2e582b-c079-11ed-a85d-9c5c8ec2126c,game_state
24,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.019966284995462e-08, 1.2364604629055975e-07...",6440534d-c078-11ed-b8f6-9c5c8ec2126c,game_state
25,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.700952623195917e-07, 1.2504513335898082e-07...",cef11e74-c07d-11ed-a6b7-9c5c8ec2126c,game_state
26,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.5589033353080595e-07, 1.1761855489567097e-0...",a58df3a1-c07e-11ed-9ce1-9c5c8ec2126c,game_state
27,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.677412342360185e-07, 1.3253311692551506e-07...",cf32bb6c-c07d-11ed-97eb-9c5c8ec2126c,game_state
28,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.104458533518482e-07, 8.559667463714504e-08,...",ef9c6a51-c07a-11ed-85cd-9c5c8ec2126c,game_state
29,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2076469602106954e-07, 1.1096024365997437e-0...",f21bbdca-c07a-11ed-990a-9c5c8ec2126c,game_state
30,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.1993327575510193e-07, 1.0045284426496437e-0...",f1dbb5f3-c07a-11ed-8241-9c5c8ec2126c,game_state

In [22]:
low_performing_list = df[df['value_at_argmax']<=1]['id'].tolist()
low_performing_list
#Image.open(f"{root_dir}\\{df[0:2]['id'].tolist()[0]}.png")

['c7f94c7d-c07a-11ed-a56b-9c5c8ec2126c',
 'a51e0ccb-c07d-11ed-947a-9c5c8ec2126c',
 'e51a3ef3-c077-11ed-b603-9c5c8ec2126c',
 'e76698b1-c077-11ed-a9cc-9c5c8ec2126c',
 '109d28de-c078-11ed-a947-9c5c8ec2126c',
 '3b16dcd2-c078-11ed-8077-9c5c8ec2126c',
 'dfd6cc18-c078-11ed-8da8-9c5c8ec2126c',
 '8509ecca-c079-11ed-ad3c-9c5c8ec2126c',
 '3227d4d7-c079-11ed-afd0-9c5c8ec2126c',
 '325bb576-c079-11ed-bd92-9c5c8ec2126c',
 'b690f737-c078-11ed-990a-9c5c8ec2126c',
 '5b887e48-c079-11ed-879b-9c5c8ec2126c',
 '8d6b9004-c078-11ed-b784-9c5c8ec2126c',
 '0902b69b-c079-11ed-9b37-9c5c8ec2126c',
 'ccabceed-c07d-11ed-af4d-9c5c8ec2126c',
 'ae2e582b-c079-11ed-a85d-9c5c8ec2126c',
 '6440534d-c078-11ed-b8f6-9c5c8ec2126c',
 'cef11e74-c07d-11ed-a6b7-9c5c8ec2126c',
 'cf32bb6c-c07d-11ed-97eb-9c5c8ec2126c',
 'ef9c6a51-c07a-11ed-85cd-9c5c8ec2126c',
 'f1dbb5f3-c07a-11ed-8241-9c5c8ec2126c',
 'f21bbdca-c07a-11ed-990a-9c5c8ec2126c']

In [23]:
#import shutil
#for item in low_performing_list:
    #shutil.move(f"{root_dir}\\images\\{item}.png", f"O:\\source\\repos\\EVE-Online-Bot\\training_data\\unclass\\{item}.png")