In [78]:
from tqdm import tqdm
import json
from PIL import Image
import pandas as pd

In [79]:
lines = ''
root_dir = '\\\\databrick\\Active Server Drive\\log_dir\\eve_miner'
with open(f"{root_dir}\\miner_2023-03-11_18-45-16_185599.log") as f:
    lines = f.readlines()

In [80]:
class_lines = []
for line in tqdm(lines):
    if 'Current Screen Classification:' in line or 'Current Screen:' in line:
        index = line.find('{')
        class_lines.append(json.loads(line[index:-1].replace("'", '"').replace('UUID("', '"').replace('")', '"').replace("True", '1').replace("False", '0')))

100%|████████████████████████████████████████████████████████████████████████████████████████| 195/195 [00:00<?, ?it/s]

In [81]:
len(class_lines)

12

In [82]:
class_lines[0]

{'argmax_index': 2,
 'value_at_argmax': 0.9999863,
 'pass_general_tollerance': 1,
 'class': 'in_flight',
 'classes': ['char_select', 'connection_lost', 'in_flight', 'in_hanger'],
 'scores': [1.5087435940586147e-06,
  2.4136638785421383e-06,
  0.9999862909317017,
  9.687637430033647e-06],
 'id': '7caf10a0-c06f-11ed-8b51-9c5c8ec2126c',
 'model': 'game_state'}

In [83]:
df = pd.DataFrame(class_lines)
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,2,0.999986,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.5087435940586147e-06, 2.4136638785421383e-0...",7caf10a0-c06f-11ed-8b51-9c5c8ec2126c,game_state
1,2,0.999986,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.6064994952103007e-06, 2.554932507337071e-06...",7ee21b74-c06f-11ed-a129-9c5c8ec2126c,game_state
2,2,0.999997,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9526754613252706e-07, 6.639879188696796e-07...",a805b331-c06f-11ed-a4e8-9c5c8ec2126c,game_state
3,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.533491200689241e-07, 2.6254397766933835e-07...",d126f7a6-c06f-11ed-8ee0-9c5c8ec2126c,game_state
4,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.074509524163659e-07, 4.822873620469181e-07,...",fa91a253-c06f-11ed-8dec-9c5c8ec2126c,game_state
5,2,0.999997,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.1037681108282413e-07, 4.896335781268135e-07...",23a78941-c070-11ed-963c-9c5c8ec2126c,game_state
6,2,0.999997,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.756627341364947e-07, 6.098063067838666e-07,...",4ccb25f0-c070-11ed-85d1-9c5c8ec2126c,game_state
7,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.036937871707778e-07, 4.704390050846996e-07,...",75e8afd2-c070-11ed-8c77-9c5c8ec2126c,game_state
8,2,0.999997,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.114154256105394e-07, 5.106516596242727e-07,...",9f01a18d-c070-11ed-9a8a-9c5c8ec2126c,game_state
9,2,0.999997,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.1165367058983975e-07, 5.11067696606915e-07,...",9f2f6afe-c070-11ed-a864-9c5c8ec2126c,game_state
10,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.4656352220754343e-07, 2.4838098511281714e-0...",c84aee9b-c070-11ed-85b8-9c5c8ec2126c,game_state
11,2,0.999997,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0613406093161757e-07, 5.081923859506787e-07...",f165d69f-c070-11ed-a46b-9c5c8ec2126c,game_state

In [84]:
df = df.sort_values(by='value_at_argmax', ascending=True).reset_index()
del df['index']
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,2,0.999986,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.6064994952103007e-06, 2.554932507337071e-06...",7ee21b74-c06f-11ed-a129-9c5c8ec2126c,game_state
1,2,0.999986,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.5087435940586147e-06, 2.4136638785421383e-0...",7caf10a0-c06f-11ed-8b51-9c5c8ec2126c,game_state
2,2,0.999997,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9526754613252706e-07, 6.639879188696796e-07...",a805b331-c06f-11ed-a4e8-9c5c8ec2126c,game_state
3,2,0.999997,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.756627341364947e-07, 6.098063067838666e-07,...",4ccb25f0-c070-11ed-85d1-9c5c8ec2126c,game_state
4,2,0.999997,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0613406093161757e-07, 5.081923859506787e-07...",f165d69f-c070-11ed-a46b-9c5c8ec2126c,game_state
5,2,0.999997,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.1037681108282413e-07, 4.896335781268135e-07...",23a78941-c070-11ed-963c-9c5c8ec2126c,game_state
6,2,0.999997,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.114154256105394e-07, 5.106516596242727e-07,...",9f01a18d-c070-11ed-9a8a-9c5c8ec2126c,game_state
7,2,0.999997,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.1165367058983975e-07, 5.11067696606915e-07,...",9f2f6afe-c070-11ed-a864-9c5c8ec2126c,game_state
8,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.074509524163659e-07, 4.822873620469181e-07,...",fa91a253-c06f-11ed-8dec-9c5c8ec2126c,game_state
9,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.036937871707778e-07, 4.704390050846996e-07,...",75e8afd2-c070-11ed-8c77-9c5c8ec2126c,game_state
10,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.533491200689241e-07, 2.6254397766933835e-07...",d126f7a6-c06f-11ed-8ee0-9c5c8ec2126c,game_state
11,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.4656352220754343e-07, 2.4838098511281714e-0...",c84aee9b-c070-11ed-85b8-9c5c8ec2126c,game_state

In [85]:
low_performing_list = df[df['value_at_argmax']<=1]['id'].tolist()
low_performing_list
#Image.open(f"{root_dir}\\{df[0:2]['id'].tolist()[0]}.png")

['7ee21b74-c06f-11ed-a129-9c5c8ec2126c',
 '7caf10a0-c06f-11ed-8b51-9c5c8ec2126c',
 'a805b331-c06f-11ed-a4e8-9c5c8ec2126c',
 '4ccb25f0-c070-11ed-85d1-9c5c8ec2126c',
 'f165d69f-c070-11ed-a46b-9c5c8ec2126c',
 '23a78941-c070-11ed-963c-9c5c8ec2126c',
 '9f01a18d-c070-11ed-9a8a-9c5c8ec2126c',
 '9f2f6afe-c070-11ed-a864-9c5c8ec2126c',
 'fa91a253-c06f-11ed-8dec-9c5c8ec2126c',
 '75e8afd2-c070-11ed-8c77-9c5c8ec2126c',
 'd126f7a6-c06f-11ed-8ee0-9c5c8ec2126c',
 'c84aee9b-c070-11ed-85b8-9c5c8ec2126c']

In [86]:
#import shutil
#for item in low_performing_list:
    #shutil.move(f"{root_dir}\\images\\{item}.png", f"O:\\source\\repos\\EVE-Online-Bot\\training_data\\unclass\\{item}.png")

FileNotFoundError: [Errno 2] No such file or directory: '\\\\databrick\\Active Server Drive\\log_dir\\eve_miner\\images\\7ee21b74-c06f-11ed-a129-9c5c8ec2126c.png'