In [91]:
from tqdm import tqdm
import json
from PIL import Image
import pandas as pd

In [92]:
lines = ''
root_dir = '\\\\databrick\\Active Server Drive\\log_dir\\eve_miner'
with open(f"{root_dir}\\miner_2023-03-11_19-17-44_219489.log") as f:
    lines = f.readlines()

In [93]:
class_lines = []
for line in tqdm(lines):
    if 'Current Screen Classification:' in line or 'Current Screen:' in line:
        index = line.find('{')
        class_lines.append(json.loads(line[index:-1].replace("'", '"').replace('UUID("', '"').replace('")', '"').replace("True", '1').replace("False", '0')))

100%|████████████████████████████████████████████████████████████████████████████| 279/279 [00:00<00:00, 278754.36it/s]

In [94]:
len(class_lines)

32

In [95]:
class_lines[0]

{'argmax_index': 2,
 'value_at_argmax': 0.9999976,
 'pass_general_tollerance': 1,
 'class': 'in_flight',
 'classes': ['char_select', 'connection_lost', 'in_flight', 'in_hanger'],
 'scores': [6.463633894782106e-07,
  5.786481551695033e-07,
  0.999997615814209,
  1.1745007668650942e-06],
 'id': '06252ff5-c074-11ed-a754-9c5c8ec2126c',
 'model': 'game_state'}

In [96]:
df = pd.DataFrame(class_lines)
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[6.463633894782106e-07, 5.786481551695033e-07,...",06252ff5-c074-11ed-a754-9c5c8ec2126c,game_state
1,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[6.533522878271469e-07, 5.90492163610179e-07, ...",0861ac93-c074-11ed-8b9d-9c5c8ec2126c,game_state
2,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.652917802630327e-07, 1.712107433604615e-07,...",31fa8de6-c074-11ed-b4b2-9c5c8ec2126c,game_state
3,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.509306408972407e-08, 7.344257113572894e-08,...",5b31f8dc-c074-11ed-91d0-9c5c8ec2126c,game_state
4,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2900369483759278e-07, 1.2709249119779997e-0...",846c004e-c074-11ed-9cbe-9c5c8ec2126c,game_state
5,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2823791450955468e-07, 1.2684631656156853e-0...",adaa117a-c074-11ed-9333-9c5c8ec2126c,game_state
6,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.511214833271879e-07, 1.6055226126354682e-07...",d6ef3cf9-c074-11ed-aa27-9c5c8ec2126c,game_state
7,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2375534197417437e-07, 1.2020613837648852e-0...",007f340a-c075-11ed-89b3-9c5c8ec2126c,game_state
8,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.3054376779564336e-07, 1.3438062751447433e-0...",29bc1df2-c075-11ed-9073-9c5c8ec2126c,game_state
9,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.305930794615051e-07, 1.3404195442490163e-07...",29fb4709-c075-11ed-a9e3-9c5c8ec2126c,game_state
10,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0116438292916428e-07, 1.75131205537582e-07,...",503f80a4-c075-11ed-8a03-9c5c8ec2126c,game_state
11,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.009632282806706e-07, 1.750180018689207e-07,...",507ec8a9-c075-11ed-9b43-9c5c8ec2126c,game_state
12,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9917696647553385e-07, 1.7286980380504247e-0...",5264ce20-c075-11ed-aab9-9c5c8ec2126c,game_state
13,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0020114277485845e-07, 1.7389199058470695e-0...",52a33b36-c075-11ed-a05e-9c5c8ec2126c,game_state
14,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9945562712564424e-07, 1.730060432691971e-07...",54826c4e-c075-11ed-8b73-9c5c8ec2126c,game_state
15,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9941225559705344e-07, 1.7305124799804616e-0...",54c28b56-c075-11ed-8e9a-9c5c8ec2126c,game_state
16,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9966725517406303e-07, 1.7347574043924396e-0...",56a02630-c075-11ed-a8ba-9c5c8ec2126c,game_state
17,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9965754916029255e-07, 1.733336887355108e-07...",56e05412-c075-11ed-b0ee-9c5c8ec2126c,game_state
18,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.011835675830298e-07, 1.7492222070814023e-07...",58c0dffb-c075-11ed-98b6-9c5c8ec2126c,game_state
19,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0102207543004624e-07, 1.7478565439432714e-0...",59003a5d-c075-11ed-b1fd-9c5c8ec2126c,game_state
20,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0135784950525704e-07, 1.752829206225215e-07...",5ae0e784-c075-11ed-be27-9c5c8ec2126c,game_state
21,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0155016500211786e-07, 1.757068588403854e-07...",5b20326d-c075-11ed-a921-9c5c8ec2126c,game_state
22,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0192071303881676e-07, 1.759025138881043e-07...",5cfe9749-c075-11ed-b544-9c5c8ec2126c,game_state
23,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0200776873480208e-07, 1.7592886081274628e-0...",5d3de4ff-c075-11ed-bb7e-9c5c8ec2126c,game_state
24,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0176017301309912e-07, 1.7509296412754338e-0...",5f1b818f-c075-11ed-9dd3-9c5c8ec2126c,game_state
25,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.017193878600665e-07, 1.751671163674473e-07,...",5f5ba6df-c075-11ed-99c5-9c5c8ec2126c,game_state
26,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0194266880935174e-07, 1.762780215130988e-07...",613c4344-c075-11ed-8675-9c5c8ec2126c,game_state
27,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0169245829038118e-07, 1.7581682243417163e-0...",617ac73d-c075-11ed-b2bc-9c5c8ec2126c,game_state
28,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9945505869145563e-07, 1.7364408222420025e-0...",635cf870-c075-11ed-9589-9c5c8ec2126c,game_state
29,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9936642559059692e-07, 1.7345357150588825e-0...",639b86b7-c075-11ed-b669-9c5c8ec2126c,game_state
30,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9890400437816425e-07, 1.732185097580441e-07...",65791d54-c075-11ed-92e2-9c5c8ec2126c,game_state
31,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.988687188259064e-07, 1.7302384947015526e-07...",65b9371e-c075-11ed-a1d2-9c5c8ec2126c,game_state

In [97]:
df = df.sort_values(by='value_at_argmax', ascending=True).reset_index()
del df['index']
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[6.463633894782106e-07, 5.786481551695033e-07,...",06252ff5-c074-11ed-a754-9c5c8ec2126c,game_state
1,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[6.533522878271469e-07, 5.90492163610179e-07, ...",0861ac93-c074-11ed-8b9d-9c5c8ec2126c,game_state
2,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9936642559059692e-07, 1.7345357150588825e-0...",639b86b7-c075-11ed-b669-9c5c8ec2126c,game_state
3,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9945505869145563e-07, 1.7364408222420025e-0...",635cf870-c075-11ed-9589-9c5c8ec2126c,game_state
4,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0169245829038118e-07, 1.7581682243417163e-0...",617ac73d-c075-11ed-b2bc-9c5c8ec2126c,game_state
5,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0194266880935174e-07, 1.762780215130988e-07...",613c4344-c075-11ed-8675-9c5c8ec2126c,game_state
6,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.017193878600665e-07, 1.751671163674473e-07,...",5f5ba6df-c075-11ed-99c5-9c5c8ec2126c,game_state
7,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0176017301309912e-07, 1.7509296412754338e-0...",5f1b818f-c075-11ed-9dd3-9c5c8ec2126c,game_state
8,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0200776873480208e-07, 1.7592886081274628e-0...",5d3de4ff-c075-11ed-bb7e-9c5c8ec2126c,game_state
9,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0192071303881676e-07, 1.759025138881043e-07...",5cfe9749-c075-11ed-b544-9c5c8ec2126c,game_state
10,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0155016500211786e-07, 1.757068588403854e-07...",5b20326d-c075-11ed-a921-9c5c8ec2126c,game_state
11,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0135784950525704e-07, 1.752829206225215e-07...",5ae0e784-c075-11ed-be27-9c5c8ec2126c,game_state
12,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0102207543004624e-07, 1.7478565439432714e-0...",59003a5d-c075-11ed-b1fd-9c5c8ec2126c,game_state
13,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.011835675830298e-07, 1.7492222070814023e-07...",58c0dffb-c075-11ed-98b6-9c5c8ec2126c,game_state
14,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9965754916029255e-07, 1.733336887355108e-07...",56e05412-c075-11ed-b0ee-9c5c8ec2126c,game_state
15,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9966725517406303e-07, 1.7347574043924396e-0...",56a02630-c075-11ed-a8ba-9c5c8ec2126c,game_state
16,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9941225559705344e-07, 1.7305124799804616e-0...",54c28b56-c075-11ed-8e9a-9c5c8ec2126c,game_state
17,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9945562712564424e-07, 1.730060432691971e-07...",54826c4e-c075-11ed-8b73-9c5c8ec2126c,game_state
18,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0020114277485845e-07, 1.7389199058470695e-0...",52a33b36-c075-11ed-a05e-9c5c8ec2126c,game_state
19,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9917696647553385e-07, 1.7286980380504247e-0...",5264ce20-c075-11ed-aab9-9c5c8ec2126c,game_state
20,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.009632282806706e-07, 1.750180018689207e-07,...",507ec8a9-c075-11ed-9b43-9c5c8ec2126c,game_state
21,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[2.0116438292916428e-07, 1.75131205537582e-07,...",503f80a4-c075-11ed-8a03-9c5c8ec2126c,game_state
22,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.511214833271879e-07, 1.6055226126354682e-07...",d6ef3cf9-c074-11ed-aa27-9c5c8ec2126c,game_state
23,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.652917802630327e-07, 1.712107433604615e-07,...",31fa8de6-c074-11ed-b4b2-9c5c8ec2126c,game_state
24,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9890400437816425e-07, 1.732185097580441e-07...",65791d54-c075-11ed-92e2-9c5c8ec2126c,game_state
25,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.988687188259064e-07, 1.7302384947015526e-07...",65b9371e-c075-11ed-a1d2-9c5c8ec2126c,game_state
26,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.305930794615051e-07, 1.3404195442490163e-07...",29fb4709-c075-11ed-a9e3-9c5c8ec2126c,game_state
27,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.3054376779564336e-07, 1.3438062751447433e-0...",29bc1df2-c075-11ed-9073-9c5c8ec2126c,game_state
28,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2375534197417437e-07, 1.2020613837648852e-0...",007f340a-c075-11ed-89b3-9c5c8ec2126c,game_state
29,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2823791450955468e-07, 1.2684631656156853e-0...",adaa117a-c074-11ed-9333-9c5c8ec2126c,game_state
30,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2900369483759278e-07, 1.2709249119779997e-0...",846c004e-c074-11ed-9cbe-9c5c8ec2126c,game_state
31,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.509306408972407e-08, 7.344257113572894e-08,...",5b31f8dc-c074-11ed-91d0-9c5c8ec2126c,game_state

In [85]:
low_performing_list = df[df['value_at_argmax']<=1]['id'].tolist()
low_performing_list
#Image.open(f"{root_dir}\\{df[0:2]['id'].tolist()[0]}.png")

['7ee21b74-c06f-11ed-a129-9c5c8ec2126c',
 '7caf10a0-c06f-11ed-8b51-9c5c8ec2126c',
 'a805b331-c06f-11ed-a4e8-9c5c8ec2126c',
 '4ccb25f0-c070-11ed-85d1-9c5c8ec2126c',
 'f165d69f-c070-11ed-a46b-9c5c8ec2126c',
 '23a78941-c070-11ed-963c-9c5c8ec2126c',
 '9f01a18d-c070-11ed-9a8a-9c5c8ec2126c',
 '9f2f6afe-c070-11ed-a864-9c5c8ec2126c',
 'fa91a253-c06f-11ed-8dec-9c5c8ec2126c',
 '75e8afd2-c070-11ed-8c77-9c5c8ec2126c',
 'd126f7a6-c06f-11ed-8ee0-9c5c8ec2126c',
 'c84aee9b-c070-11ed-85b8-9c5c8ec2126c']

In [86]:
#import shutil
#for item in low_performing_list:
    #shutil.move(f"{root_dir}\\images\\{item}.png", f"O:\\source\\repos\\EVE-Online-Bot\\training_data\\unclass\\{item}.png")

FileNotFoundError: [Errno 2] No such file or directory: '\\\\databrick\\Active Server Drive\\log_dir\\eve_miner\\images\\7ee21b74-c06f-11ed-a129-9c5c8ec2126c.png'